### PR TITLE
AWSCore style

### PR DESCRIPTION
**Pull request by samuelpowell**
Pass AWS configuration to actions as argument

### CODE REVIEW

**Comment by samuelpowell** [comment]
Wrong repo, sorry for the noise.

**Comment by keith-mason-conning** [comment]
No worries.  We actually have been working on an AWSCore version of this that hasn't yet been posted.  We find AWSCore.jl easier to leverage than AWS.jl.  I would like to review this PR anyhow and perhaps collaborate on direction of the project.  I assume you're going to send it to https://github.com/dls/DynamoDB.jl?

**Comment by samuelpowell** [comment]
I agree regarding [AWSCore.jl](https://github.com/samoconnor/AWSCore.jl), and I wonder if in the future this and @samoconnor's associated AWS packages might be adopted by @JuliaCloud, if @samoconnor and @tanmaykm / @tkelman were all in favour.

Regarding DynamoDB, I wasn't planning on opening a PR to [dls/DynamoDB.jl](https://github.com/dls/DynamoDB.jl) since i) the repository looks stale, and ii) I would like to try move the interface towards the other modules written by @samoconnor, by which point it won't much resemble the original codebase! 

For the moment, I just need something that works for my own purposes, and don't have much time to make it pretty. That said, I'm more than happy to open a PR against this repository on the understanding that I may not have the time to fix anything highlighted in review.

**Comment by samoconnor** [comment]
Hi @samuelpowell, @s2maki,

I'm open to moving AWSCore.jl et all to @JuliaCloud if you think that would be useful.

@tanmaykm? @tanmaykm?

There are at least a few places where the AWSCore already has features that people are asking for in AWS.jl:

 - https://github.com/JuliaCloud/AWS.jl/issues/57

 - https://github.com/JuliaCloud/AWS.jl/issues/39#issuecomment-216014900

 - https://github.com/JuliaCloud/AWS.jl/issues/83#issuecomment-289620185

 - https://github.com/JuliaCloud/AWS.jl/pull/73#discussion_r82535091

**Comment by keith-mason-conning** [comment]
With your agreement, I'd like to make this proposal to the Julia developers as well.  Are you planning to be at JuliaCon in California this summer?

**Comment by samoconnor** [comment]
@s2maki I'm happy for you to make the proposal.
Unfortunately I won't be at JuliaCon.

**Comment by samoconnor** [comment]
FYI I've recently updated AWSCore et all with a few v0.6 tweaks and got the travis tests passing again: https://github.com/samoconnor/AWSCore.jl

**Comment by samuelpowell** [comment]
Thanks @samoconnor!

**Comment by tanmaykm** [comment]
I think it will be good to have AWSCore and the related packages in JuliaCloud.
Hi @samoconnor, I could add you to the organization to facilitate the movement.

**Comment by samoconnor** [comment]
Hi @tanmaykm, I'd be happy for you to add me to the organisation.

**Comment by tanmaykm** [comment]
Thanks @samoconnor ! I have sent an invite.

**Pull request closed without merging**
